//Copyright (c) Microsoft Corporation. All rights reserved.
//Licensed under the MIT License.
import org.apache.kafka.clients.producer.Callback;
import org.apache.kafka.clients.producer.Producer;
import org.apache.kafka.clients.producer.ProducerRecord;
import org.apache.kafka.clients.producer.RecordMetadata;
import java.sql.Timestamp;
import java.util.Random;

public class TestDataReporter implements Runnable {

    private static final int NUM_MESSAGES = 100;
    private final String TOPIC;

    private Producer<Long, String> producer;

    public TestDataReporter(final Producer<Long, String> producer, String TOPIC) {
        this.producer = producer;
        this.TOPIC = TOPIC;
    }

    @Override
    public void run() {
        for(int i = 0; i < NUM_MESSAGES; i++) {                
            long time = System.currentTimeMillis();
            String msg = generateMessage();
            System.out.println("Test Data #" + i + " from thread #" + Thread.currentThread().getId());
            
            final ProducerRecord<Long, String> record = new ProducerRecord<Long, String>(TOPIC, time, msg);
            producer.send(record, new Callback() {
                public void onCompletion(RecordMetadata metadata, Exception exception) {
                    if (exception != null) {
                        System.out.println(exception);
                        System.exit(1);
                    }
                }
            });
        }
        System.out.println("Finished sending " + NUM_MESSAGES + " messages from thread #" + Thread.currentThread().getId() + "!");
    }

    // generate random JSON message with a timestamp, temperature, and humidity field
    // generated by Copilot
    private String generateMessage() {
        Random rand = new Random();
        Timestamp timestamp = new Timestamp(System.currentTimeMillis());
        int temperature = rand.nextInt(100);
        int humidity = rand.nextInt(100);
        return "{\"timestamp\": \"" + timestamp + "\", \"temperature\": " + temperature + ", \"humidity\": " + humidity + "}";
    }
}